[package]
name = "webapp"
version = "0.1.16"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Critical for wasm libraries

[dependencies]
webui = { git = "https://github.com/StoicDreams/WebUI", branch = "main", features = [] }
serde = { version = "1.0", features = ["derive"] }
